id: IAF6ADAC4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:50:13+00:00'
last_modified: '2022-06-08T05:48:22.806341+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20214
  title: མཚོ་ལྷོ་ཁུལ་གྱི་དགོན་སྡེ་ཁག་གི་ལོ་རྒྱུས་སྙིང་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    01AA:
      image_group_id: I4197
      title: ''
      total_pages: 799
      order: 1
      base_file: 01AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
